### ISSUE TITLE
postgres/Dockerfile copying to wrong destination

### ISSUE THREAD

**Issue by rcruicks** [alessfg/docker-ethercis#2]
tried getting this to work on IBM Bluemix - found that the COPY of the 01 and 02 scripts don't show up -- missing / on target directory

< COPY ./01_db_creation.sh ./docker-entrypoint-initdb.d

> COPY ./01_db_creation.sh ./docker-entrypoint-initdb.d/
> < COPY ./02_db_init.sh ./docker-entrypoint-initdb.d
> COPY ./02_db_init.sh ./docker-entrypoint-initdb.d/

**Comment by alessfg** [comment]
I have just tested on Windows 10 and Ubuntu and it seems to be running correctly on both platforms. Which OS does the IBM Bluemix system use? The files might not be copying correctly due to some OS specific path inference.

Can you try replacing `COPY ./01_db_creation.sh ./docker-entrypoint-initdb.d` by `COPY ./01_db_creation.sh ./docker-entrypoint-initdb.d/01_db_creation.sh` and `COPY ./02_db_init.sh ./docker-entrypoint-initdb.d` by `COPY ./02_db_init.sh ./docker-entrypoint-initdb.d/02_db_init.sh` in the postgres Dockerfile and see if it works?

**Comment by rcruicks** [comment]
that would work too - because the directory doesn't exist before the first copy.it is created as a file, then overwritten by the second copy.
